"""Pydantic models and loader for the tier-1 web allowlist.

The allowlist is generated by ``ingest.extract_web_allowlist`` from
upstream documentation (README + tier-5 web-platforms-index) and
consumed by the search worker (Step 8) to issue ``site:<domain>``
queries against trusted sources before falling through to open Serper.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

DEFAULT_ALLOWLIST_PATH = Path("backend/data/tier1_web_sources.yaml")


WebAccess = Literal["site_search", "api", "auth_required"]


# EU + EFTA member countries that should match an EU_27 coverage tag.
# Conservative: if a country is in here, querying it expands to also
# match sources tagged "EU_27" or "global".
_EU_LIKE_COUNTRIES = {
    "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES", "FI",
    "FR", "GR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT",
    "NL", "PL", "PT", "RO", "SE", "SI", "SK",
    # EFTA / closely-aligned non-members where EU stats often include them.
    "CH", "IS", "LI", "NO", "UK", "GB",
}


def _expand_country(country: str) -> set[str]:
    """Return all coverage tags a country should match against.

    DE matches sources tagged DE, EU_27, or global.  An unknown country
    only matches itself + global.
    """
    upper = country.upper()
    expanded = {upper, "global", "GLOBAL"}
    if upper in _EU_LIKE_COUNTRIES:
        expanded.add("EU_27")
    return expanded


class CoverageHint(BaseModel):
    """What a tier-1 source covers — used for coverage matching at search time."""

    model_config = ConfigDict(extra="allow")

    countries: list[str] = Field(default_factory=list)
    cities: list[str] = Field(default_factory=list)
    fields: list[str] = Field(default_factory=list)
    scope: list[str] = Field(default_factory=list)


class Tier1WebSource(BaseModel):
    """One trusted web source the search worker hits before open Serper."""

    id: str
    name: str
    domain: str
    urls: list[str] = Field(default_factory=list)
    access: WebAccess = "site_search"
    coverage: CoverageHint = Field(default_factory=CoverageHint)
    excluded_paths: list[str] = Field(default_factory=list)
    notes: str = ""


class Tier1WebAllowlist(BaseModel):
    version: int = 1
    sources: list[Tier1WebSource] = Field(default_factory=list)

    def by_domain(self) -> dict[str, Tier1WebSource]:
        return {source.domain: source for source in self.sources}

    def matching(
        self,
        *,
        country: str | None = None,
        cities: list[str] | None = None,
        fields: list[str] | None = None,
        scope: list[str] | None = None,
    ) -> list[Tier1WebSource]:
        """Return sources whose coverage overlaps with at least one of the inputs.

        Empty / missing inputs are treated as "any" — they don't constrain the
        match.  A source matches when it has *no* coverage signal in a given
        dimension (broad coverage) OR overlaps with the requested values.
        """
        cities_set = {c.casefold() for c in cities or [] if c}
        fields_set = {f.casefold() for f in fields or [] if f}
        scope_set = {s.casefold() for s in scope or [] if s}
        country_keys = (
            {c.casefold() for c in _expand_country(country)} if country else set()
        )

        matches: list[Tier1WebSource] = []
        for source in self.sources:
            cov = source.coverage
            if country_keys and cov.countries:
                source_countries = {c.casefold() for c in cov.countries}
                if not (country_keys & source_countries):
                    continue
            if cities_set and cov.cities:
                if not (cities_set & {c.casefold() for c in cov.cities}):
                    continue
            if fields_set and cov.fields:
                if not (fields_set & {f.casefold() for f in cov.fields}):
                    continue
            if scope_set and cov.scope:
                if not (scope_set & {s.casefold() for s in cov.scope}):
                    continue
            matches.append(source)
        return matches


def load_tier1_web_allowlist(path: Path | None = None) -> Tier1WebAllowlist:
    """Load and validate the tier-1 web allowlist yaml."""
    allowlist_path = path or DEFAULT_ALLOWLIST_PATH
    if not allowlist_path.exists():
        raise FileNotFoundError(f"Tier-1 web allowlist not found: {allowlist_path}")
    raw = yaml.safe_load(allowlist_path.read_text(encoding="utf-8")) or {}
    return Tier1WebAllowlist.model_validate(raw)


__all__ = [
    "CoverageHint",
    "DEFAULT_ALLOWLIST_PATH",
    "Tier1WebAllowlist",
    "Tier1WebSource",
    "WebAccess",
    "load_tier1_web_allowlist",
]
