export const DEFAULT_CONTEXT_TOKEN_CAP = 250000;
export const CHAT_JOB_POLL_INTERVAL_MS = 2000;
export const CHAT_SEND_RECOVERY_POLL_INTERVAL_MS = 2000;
export const CHAT_SEND_RECOVERY_TIMEOUT_MS = 180000;
